### ISSUE TITLE
How create config file?

### ISSUE THREAD

**Issue by leonardofoodology** [fwd/database#1]
How do I pass the connection data from my database?

is there a difference in using a relational database or non relational database? 

Where do I place the models (entities)?

How do I make relationships between tables?

**Comment by nano2dev** [comment]
**Sorry, Support for Relational Databases is NOT available yet.** 

**fwd/database** is a JSON database ONLY. 

Here are some examples of how to use. All data is saved to a .data folder or database.json file (if using lowdb plugin)

```javascript

// npm install fwd/database

const database = require('@fwd/database')
  
;(async () => {
  
  // create user
  
  var user = await database.create('users', {
      name: 'John'
  })
  
  console.log( "Created user with id of", user.id )
  
  // create another 'model' with a relationship
  
  var pet = await database.create('pets', {
      name: 'Sparky',
      ownerId: user.id
  })
  
  // find pet by owner id
  
  var pet = await database.findOne('pets', {
      ownerId: user.id
  })

  // and vice versa

  var user = await database.findOne('users', { 
    id: pet.ownerId 
  })

})

```

Does this answer your question?
